### PR TITLE
Add localization policy

### PR DESCRIPTION
**Pull request by sudocode1**
Change as you wish & merge whenever.

### CODE REVIEW

**Comment by jbmagination** [comment]
AFAIK `.github` does not support `LOCALIZATION.md`. This would've been a nice change, though!

**Comment by sudocode1** [comment]
I am aware this is not supported, but this policy should be centralized within `.github` so it's at quick access to contributors and we can link to it when people add unsupported localizations. Just an idea, though.

**Comment by jbmagination** [comment]
Not a bad idea but we can probably put this somewhere else. For example, that `other` repository we have ([DefinityTeam/other](https://github.com/DefinityTeam/other)

**Comment by sudocode1** [comment]
That is true. I'll decide later on today.

**Pull request closed without merging**
